# Generated by Django 4.2.5 on 2023-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_recipe_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_date",
            field=models.DateField(auto_now=True, verbose_name="date"),
        ),
    ]
