# Generated by Django 4.2.5 on 2023-09-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "calorie",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="calorie"
                    ),
                ),
                (
                    "protein",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="protein"
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        blank=True,
                        choices=[("GEN", "generic"), ("CUS", "custom")],
                        max_length=3,
                        null=True,
                        verbose_name="food type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiry",
                    models.DateField(blank=True, null=True, verbose_name="expiry"),
                ),
                (
                    "purchased_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="purchased on"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_food_items",
                        to="food.fooditem",
                        verbose_name="item",
                    ),
                ),
            ],
        ),
    ]
